import React from "react";
import {
  SiReact, SiNextdotjs, SiNodedotjs, SiExpress, SiMongodb, SiTailwindcss,
  SiTypescript, SiJavascript, SiSocketdotio, SiRedux, SiGit, SiDocker,
  SiPostgresql, SiMysql, SiFirebase, SiGraphql, SiFigma, SiVuedotjs,
  SiAngular, SiSass, SiBootstrap, SiJquery, SiWebpack, SiBabel,
  SiCplusplus, SiPython, SiJupyter, SiPandas, SiOpencv, SiPytorch,
  SiTensorflow, SiScikitlearn, SiNumpy, SiThreedotjs, SiBlender, SiUnity,
  SiUnrealengine, SiGooglecloud, SiDigitalocean, SiCloudflare,
  SiHeroku, SiNetlify, SiVercel, SiLinux, SiNginx, SiGitlab, SiGithubactions,
  SiKubernetes, SiAnsible, SiTerraform, SiSwagger, SiPostman, SiVim,
  SiFlask, SiDjango, SiFastapi,
} from "react-icons/si";
import { Code2, Terminal } from "lucide-react";

const TECH_ICONS = {
  "react":            SiReact,
  "react.js":         SiReact,
  "next.js":          SiNextdotjs,
  "nextjs":           SiNextdotjs,
  "node.js":          SiNodedotjs,
  "nodejs":           SiNodedotjs,
  "express":          SiExpress,
  "express.js":       SiExpress,
  "mongodb":          SiMongodb,
  "mongo":            SiMongodb,
  "tailwind":         SiTailwindcss,
  "tailwind css":     SiTailwindcss,
  "typescript":       SiTypescript,
  "ts":               SiTypescript,
  "javascript":       SiJavascript,
  "js":               SiJavascript,
  "socket.io":        SiSocketdotio,
  "socketio":         SiSocketdotio,
  "redux":            SiRedux,
  "git":              SiGit,
  "docker":           SiDocker,
  "postgresql":       SiPostgresql,
  "postgres":         SiPostgresql,
  "mysql":            SiMysql,
  "firebase":         SiFirebase,
  "graphql":          SiGraphql,
  "figma":            SiFigma,
  "vue":              SiVuedotjs,
  "vue.js":           SiVuedotjs,
  "angular":          SiAngular,
  "sass":             SiSass,
  "scss":             SiSass,
  "bootstrap":        SiBootstrap,
  "jquery":           SiJquery,
  "webpack":          SiWebpack,
  "babel":            SiBabel,
  "c++":              SiCplusplus,
  "cpp":              SiCplusplus,
  "python":           SiPython,
  "jupyter":          SiJupyter,
  "pandas":           SiPandas,
  "opencv":           SiOpencv,
  "pytorch":          SiPytorch,
  "tensorflow":       SiTensorflow,
  "scikit-learn":     SiScikitlearn,
  "sklearn":          SiScikitlearn,
  "numpy":            SiNumpy,
  "three.js":         SiThreedotjs,
  "threejs":          SiThreedotjs,
  "blender":          SiBlender,
  "unity":            SiUnity,
  "unreal":           SiUnrealengine,
  "unreal engine":    SiUnrealengine,
  "aws":              Terminal,
  "gcp":              SiGooglecloud,
  "google cloud":     SiGooglecloud,
  "digitalocean":     SiDigitalocean,
  "cloudflare":       SiCloudflare,
  "heroku":           SiHeroku,
  "netlify":          SiNetlify,
  "vercel":           SiVercel,
  "linux":            SiLinux,
  "nginx":            SiNginx,
  "gitlab":           SiGitlab,
  "github actions":   SiGithubactions,
  "kubernetes":       SiKubernetes,
  "k8s":              SiKubernetes,
  "ansible":          SiAnsible,
  "terraform":        SiTerraform,
  "swagger":          SiSwagger,
  "postman":          SiPostman,
  "vim":              SiVim,
  "vs code":          Code2,
  "flask":            SiFlask,
  "django":           SiDjango,
  "fastapi":          SiFastapi,
};

const FUZZY_RULES = [
  { includes: "react",          icon: SiReact },
  { includes: "next",           icon: SiNextdotjs },
  { includes: "node",           icon: SiNodedotjs },
  { includes: "express",        icon: SiExpress },
  { includes: "mongo",          icon: SiMongodb },
  { includes: "tailwind",       icon: SiTailwindcss },
  { includes: "typescript",     icon: SiTypescript },
  { includes: "javascript",     icon: SiJavascript },
  { includes: "socket",         icon: SiSocketdotio },
  { includes: "redux",          icon: SiRedux },
  { includes: "docker",         icon: SiDocker },
  { includes: "postgres",       icon: SiPostgresql },
  { includes: "mysql",          icon: SiMysql },
  { includes: "firebase",       icon: SiFirebase },
  { includes: "graphql",        icon: SiGraphql },
  { includes: "figma",          icon: SiFigma },
  { includes: "vue",            icon: SiVuedotjs },
  { includes: "angular",        icon: SiAngular },
  { includes: "sass",           icon: SiSass },
  { includes: "scss",           icon: SiSass },
  { includes: "bootstrap",      icon: SiBootstrap },
  { includes: "jquery",         icon: SiJquery },
  { includes: "webpack",        icon: SiWebpack },
  { includes: "babel",          icon: SiBabel },
  { includes: "c++",            icon: SiCplusplus },
  { includes: "cpp",            icon: SiCplusplus },
  { includes: "python",         icon: SiPython },
  { includes: "jupyter",        icon: SiJupyter },
  { includes: "pandas",         icon: SiPandas },
  { includes: "opencv",         icon: SiOpencv },
  { includes: "pytorch",        icon: SiPytorch },
  { includes: "tensorflow",     icon: SiTensorflow },
  { includes: "scikit",         icon: SiScikitlearn },
  { includes: "sklearn",        icon: SiScikitlearn },
  { includes: "numpy",          icon: SiNumpy },
  { includes: "three",          icon: SiThreedotjs },
  { includes: "blender",        icon: SiBlender },
  { includes: "unity",          icon: SiUnity },
  { includes: "unreal",         icon: SiUnrealengine },
  { includes: "aws",            icon: Terminal },
  { includes: "google cloud",   icon: SiGooglecloud },
  { includes: "gcp",            icon: SiGooglecloud },
  { includes: "digitalocean",   icon: SiDigitalocean },
  { includes: "cloudflare",     icon: SiCloudflare },
  { includes: "heroku",         icon: SiHeroku },
  { includes: "netlify",        icon: SiNetlify },
  { includes: "vercel",         icon: SiVercel },
  { includes: "linux",          icon: SiLinux },
  { includes: "nginx",          icon: SiNginx },
  { includes: "gitlab",         icon: SiGitlab },
  { includes: "github",         icon: SiGithubactions },
  { includes: "git",            icon: SiGit },
  { includes: "kubernetes",     icon: SiKubernetes },
  { includes: "k8s",            icon: SiKubernetes },
  { includes: "ansible",        icon: SiAnsible },
  { includes: "terraform",      icon: SiTerraform },
  { includes: "swagger",        icon: SiSwagger },
  { includes: "postman",        icon: SiPostman },
  { includes: "vim",            icon: SiVim },
  { includes: "vs code",        icon: Code2 },
  { includes: "visual studio",  icon: Code2 },
  { includes: "flask",          icon: SiFlask },
  { includes: "django",         icon: SiDjango },
  { includes: "fastapi",        icon: SiFastapi },
  { includes: "html",           icon: Code2 },
  { includes: "css",            icon: Code2 },
  { includes: "api",            icon: Terminal },
];

export const getTechIcon = (tech) => {
  if (!tech) return Terminal;
  const key = tech.trim().toLowerCase();
  return TECH_ICONS[key] || FUZZY_RULES.find(r => key.includes(r.includes))?.icon || Terminal;
};
